### ISSUE TITLE
Apikey is missing

### ISSUE THREAD

**Issue by AjeethT** [cubiclesoft/cloud-storage-server#2]
When starting the server it shows api key is missing. In what place api key is used. Please update documentation in an understandable form.

**Comment by cubiclesoft** [comment]
Please clarify what you are talking about.  I run the server daily on multiple hosts without issue.

An API key is created via `manage.php`.  Clients connecting into the server require an API key to access the server.

**Comment by cubiclesoft** [comment]
I just realized that there might be a slight misunderstanding.  There's no GUI/web browser interface to this software.  If you attempt to connect that way, the request will be rejected.  The API is the intended mechanism for access and the SDK is there to aid in simplifying access.  This software could form the basis of GUI/web software but I mostly just use it in conjunction with Cloud Backup or various extensions.

**Comment by AjeethT** [comment]
I know that API key is used to connect to server but your documentation is not having a correct information of using the software, so please update it.

**Comment by cubiclesoft** [comment]
Ah...I see the problem.  I wrote Cloud Storage Server long before I completely documented every little thing that I write.  I also apparently forgot to link to [Cloud Storage Tools](https://github.com/cubiclesoft/cloud-storage-tools), which was written later.

I've updated the README in this repo with some more instructions.
