### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by omsenjalia** [cubiclesoft/cloud-storage-server#4]
Could I have images of this server please

**Comment by cubiclesoft** [comment]
Are you referring to something like Docker images or something more along the lines of screenshots?  For the former, I'm not aware of any.  For the latter, this is a server that presents an API.  There's not much to look at.

**Comment by omsenjalia** [comment]
Rip

**Comment by omsenjalia** [comment]
And I was talking about screenshots
